### PR TITLE
move translations out from package

### PR DESCRIPTION
**Pull request by idamir**
I'm sorry, tonight I just removed the *.po files instead of moving them.

In case of translations inside package directory, cmake install source *.po files with bash scripts and statistic files into the widget. This is incorrect.

In case of separate translations from the full package, generated *.mo files are installed into system /usr/share/locale place.

### CODE REVIEW

**Comment by idamir** [comment]
this will fix the issue #38

**Comment by solbu** [comment]
> I'm sorry, tonight I just removed the *.po files instead of moving them.

Yea, we noticed that. :-) 
I already guessed that was just an error on your end. Don't worry about it.


> In case of translations inside package directory, cmake install source *.po files with bash scripts and statistic files into the widget. This is incorrect.
> 
> In case of separate translations from the full package, generated *.mo files are installed into system /usr/share/locale place.

It's not enough to move the folder, various scripts also needs to be changed.
I have already fixed all this. See my Pull Request #39 that is already merged.

**Comment by idamir** [comment]
Oh, great!
I suggest moving out bash scripts from po/ directory to keep it clean.

**Comment by solbu** [comment]
> Oh, great! I suggest moving out bash scripts from po/ directory to keep it clean.

It's not that easy. :-)
But I suggest you close this PR as it will undo some changes and break the build process. :-)

**Pull request closed without merging**
