### PR TITLE
Fix build warnings

### PR DESCRIPTION
**Pull request by idamir**

### CODE REVIEW

**Comment by solbu** [comment]
I am speaking as a norwegian translator.

_DO NOT_ include the compiled «.mo» files!
That belongs to the user or distro compiling. It is an automated process.

Please revert the «rebuild locale files» commit.

**Comment by solbu** [comment]
I know the «.mo» files already exist in the repo, but that is an error.
Creating them belongs in the compile stage, which is something Kate needs to fix.

**Comment by idamir** [comment]
It is good idea to split the PR, but actually I have no experience with this activity. The github merges all my commits into one PR.

**Comment by solbu** [comment]
Btw, I have figured out how to properly compile the translations during the cmake compile process.
Will do some testing, and then do a pull request of my own. :-)

**Comment by idamir** [comment]
:+1: Me too :)

**Comment by solbu** [comment]
> It is good idea to split the PR, but actually I have no experience with this activity. The github merges all my commits into one PR.

The way to do separate commits is to create a new local branch from the placeSearch branch.
Like «git checkout -b translation-fixes» and do the translation changes there. Push the new branch to your fork and do a pull request from that branch to Kates placeSearch branch

**Comment by solbu** [comment]
> +1 Me too :)

Btw, the fix is that the .po files need to be in their own sub folder inside the translations folder. :-)

**Review by blackadderkate — APPROVED** [review]
I knew there was something I'd forgotten...

**Review by blackadderkate — APPROVED** [review]

**Comment by solbu** [comment]
I think the best course of action is to not store the locale folder in git.
And the build.sh file inside the translations folder recreates the entire folder structure, so your create plasmoid shell script can be changed to run it.

I can do the changes, test them and do a few pull requests that fixes these issues.
I've already found a fix (and tested it) for my newly created Issue #36 that I am preparing a Pull Request for.

**Comment by solbu** [comment]
Btw, what happened to the po files?
This PR just deleted them all.

**Comment by blackadderkate** [comment]
I just noticed that - frantically trying to revert the commit as I type...

**Comment by solbu** [comment]
Hehe. Guess he removed a folder to much. :-)

**Comment by solbu** [comment]
Btw, in case you didn't know, «gitk» is a GUI git tool that I often use to do reverts.
I can also do this step as part of my fixing up the translation compile stage, if you want.

**Comment by solbu** [comment]
> Btw, in case you didn't know, «gitk» is a GUI git tool that I often use to do reverts.

Forgot to add, you launch it by running «gitk» in the terminal, inside the git repo you are working on, and all changes comes up.
if you cd into a subfolder and run «gitk .» then only commits inside that folder shows up.

**Comment by blackadderkate** [comment]
I use Git Cola & Git Dag.

**Comment by solbu** [comment]
What ever works. :-)

**Comment by blackadderkate** [comment]
I think I got them all back!
I'm now about to remove _just_ the Locale folder...

**Comment by blackadderkate** [comment]
Uploaded a .gitignore file to ignore the locale/ folder (and .mo files), along with your suggestions from pull request #20.

**Pull request merged**
