### PR TITLE
New layouts for non-tray and some fixes.

### PR DESCRIPTION
**Pull request by evgeniy-harchenko**
Fixes: #176 , https://github.com/blackadderkate/weather-widget-2/issues/170#issuecomment-2041151837 , https://github.com/blackadderkate/weather-widget-2/issues/170#issuecomment-2041224985

### CODE REVIEW

**Comment by blackadderkate** [comment]
Thanks for your work on this.

I'll test it out as soon as I can get onto my development box (using the github app on my phone right now).

**Comment by blackadderkate** [comment]
Thanks again for your efforts on this.

I have managed to grab 5 minutes to take a quick look on an out-of-date VM on my laptop.
Initial testing looks very promising, except for the following:

The widget font size doesn't expand to fit the background when on the Desktop. Even when manually adjusted in the Configuration Appearance page.
And when docked in the panel it seemed to size incorrectly when I changed the panel orientation from vertical to horizontal -but plasma crashed shortly after so that might be my dodgy VM rather than the widget.

I'll be able to do a more thorough test when I get home.

**Comment by evgeniy-harchenko** [comment]
As for Desktop it is better to create new layout e.g. CompactItemDesktop, I guess it is a bad idea to create universal CompactItem. As a base we can use `org.kde.plasma.digitalclock`. It is just good at this, but has problems when docked in vertical panel.

**Comment by evgeniy-harchenko** [comment]
So, here is an attempt to make separate desktop layout https://github.com/evgeniy-harchenko/weather-widget-2/commit/32c5ce0d69766cb3c8e5c6b0b9219c09f62d3045 It is a draft version, so I pushed it to other branch for now.

I guess it is better to rework status section. And also I suggest to remove Compact layout from desktop version and leave it just for tray/taskbar.

**Comment by jotapesse** [comment]
Please do not discard the Compact layout. That is one of the best features of this widget and it used to work quite well for larger vertical panels - which is my use case. You can find my example screenshots and suggestions on a still open issue [#155](https://github.com/blackadderkate/weather-widget-2/issues/155).

**Comment by evgeniy-harchenko** [comment]
No no, I suggest to remove it _only_ for desktop version, like this:
image

**Comment by blackadderkate** [comment]
This is 99% there.
Although at some point I'll need to sit down at some point & figure out _how_ this works. 

Couple of issues:

1. As far as I can tell, `Property iconAndText.vertical` in `CompactItem.qml` is **always** false?
I assume this is a reference to the `main.vertical` variable and should be set accordingly?

1. The desktop widget doesn't always scale to fit the available space or respect the users' font-size settings - especially on very large widget sizes. (see the rather extreme version I created in the screenshot - yellow and red rectangles added by me for debugging purposes).

Screenshot_20240410_070445
I think the problem is that Plasma.Units.GridSize may not always be large enough for very large widgets. I have a fix for this - I will check it in shortly...

**Comment by blackadderkate** [comment]
Checked in commit 6dddf94 to hopefully FINALLY fix vertical layout & Desktop Widget issues.

**Comment by evgeniy-harchenko** [comment]
@blackadderkate as for `lastReloadedNotifier` I suggest next:

```
PlasmaComponents.Label {
    id: lastReloadedNotifier
    anchors.left: parent.left
    anchors.bottom: parent.bottom
    anchors.bottomMargin: - defaultWidgetSize * 0.05
    verticalAlignment: Text.AlignBottom
    width: parent.width
    fontSizeMode: Text.Fit
    font.pixelSize: lastReloadedNotifier.height
    minimumPixelSize: 1
    color: Kirigami.Theme.highlightColor
    text: lastReloadedText
    wrapMode: Text.NoWrap
    visible: false
    z: 1
} 
```
Especially z-index, sometimes notification is under the main text.

**Comment by evgeniy-harchenko** [comment]
Also, I guess it is better to replace this line:
`Layout.minimumHeight: iconAndText.vertical ? sizehelperText.paintedHeight : 0`
with this:
`Layout.minimumHeight: iconAndText.vertical ? sizehelperText.paintedHeight : (main.onDesktop ? sizehelperText.paintedHeight : 0)`
in `CompactItem.qml`.

**Pull request merged**
