### PR TITLE
Fix cmake warning:

### PR DESCRIPTION
**Pull request by idamir**
----
CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:112 (message):
  Your project should require at least CMake 3.16.0 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:30 (ecm_find_package_version_check)
  CMakeLists.txt:15 (find_package)
----

### CODE REVIEW

**Comment by solbu** [comment]
I reintroduced that, as my system still uses cmake 1.14.3.
Please dont increase it. :-)

**Comment by solbu** [comment]
Err, I mean 3.14.3

**Comment by idamir** [comment]
The FATAL_ERROR option is accepted but ignored by CMake 2.6 and higher. It should be specified so CMake versions 2.4 and lower fail with an error instead of just a warning.

**Comment by idamir** [comment]
Johnny, what distro do you use? What are Qt/plasma versions?

**Comment by solbu** [comment]
> Johnny, what distro do you use? What are Qt/plasma versions?

$ qtdiag |head -2
Qt 5.12.6 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 8.4.0) on "xcb" 
OS: Mageia 7 [linux version 5.10.46-desktop-1.mga7]

$ cmake --version|head -1
cmake version 3.14.3

$ rpm -qi plasma-desktop|grep Version
Version     : 5.15.4

**Comment by blackadderkate** [comment]
Just to let you know - I am running Kubuntu 20.04 LTS, and I will be very upset if someone submits a pull request which prevents me building or running my own project on my own system! :-D

Seriously though, I want to make this widget available to as many users as possible - we shouldn't change this type of setting unless there's a very good reason.

It should be pretty simple to test the cmake version in dev-build.sh and modify the CMakeList file accordingly - I'll see what I can do...

**Comment by solbu** [comment]
> It should be pretty simple to test the cmake version in dev-build.sh and modify the CMakeList file accordingly - I'll see what I can do...

When I compile this, I never use any of the shellscripts in any way, so it would not do me any good.
Everything is done by «rpmbuild» using cmake variables.
The only time I used the dev-build script was when I fixed the installer you use. :-)

In rpm packaging, we use rpm variables in the spec file for everything possible, so the compile section looks like this:
==
%cmake_kf5
%make_build
==

Your cmake line uses 4 cmake variables when compiling, rpmbuild on my system expands the variable «%cmake_kf5» to  about 68 lines of cmake variables, which properly configures the program for system wide install.

I have attatched the output of the command «rpm --eval %cmake_kf5». All those lines is what it actually takes properly compile uusing cmake.
«%make_build» is a variable that detects the number of cores on the system, and it tell make to use that number of cores for compiling, which wastly speeds up the compile time.

[rpm-cmake-variables.txt](https://github.com/blackadderkate/weather-widget-2/files/8054755/rpm-cmake-variables.txt)

**Comment by blackadderkate** [comment]
Just a couple of thoughts:

1) Would it help other Distros if you committed your RPM build configuration/script on here?
2) Do you think I should add RPM and DEB files to the releases area on here?

**Comment by martin-ms** [comment]
In addition to that one stated in the topic get another CMake warning
```
No source or binary directory provided.  Both will be assumed to be the
same as the current working directory, but note that this warning will
become a fatal error in future CMake releases.
```
System Information:
```
Operating System: Arch Linux
KDE Plasma Version: 5.24.3
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.3
Kernel Version: 5.16.14-arch1-1 (64-bit)
```

**Comment by idamir** [comment]
The issue has been fixed something else.

**Pull request closed without merging**
