### PR TITLE
Make more strings translatible

### PR DESCRIPTION
**Pull request by idamir**

### CODE REVIEW

**Comment by solbu** [comment]
Yay! You made it! :-)
Tihs looks just fine. Hopefully Kate kan merge it later today.

**Comment by idamir** [comment]
Removing the repo and forking again helped

**Comment by blackadderkate** [comment]
The commit itself looks fine.

The only thing that worries me is that someone could mis-translate the word "long" in the **data-loader.js** file.
Some translators might think it is used as an abbreviation of longtitude, but in this particular case it is used to say that the widget data was last downloaded "Long Ago".

Maybe we should insert a "translators note" somewhere = in the Readme.md or the Template (which would be an easy tweak to the merge.sh script)???

**Comment by solbu** [comment]
> Maybe we should insert a "translators note" somewhere = in the Readme.md or the Template (which would be an easy tweak to the merge.sh script)???

The comment needs to be in the actuall code, in the line just above the string. The gettext extration tools will recognize them as comments ment for translators and will automatically insert them into the pot file and subsequent into the po-files on merging with the pot.

I'll dig around to see how this is supposed to be done.

**Comment by solbu** [comment]
I have tried just about every trick that Google found, and i can't make any of them work. heh.
It seems like the best option is to change the string from long to something that is not ambiguous.

**Comment by solbu** [comment]
> I have tried just about every trick that Google found, and i can't make any of them work. heh.

Just to add, xgettext have problems extracting translator comments from javascript files.

**Comment by blackadderkate** [comment]
The only word that really works is "hours", so it would read "hours ago".
I'll push the change shortly...

**Comment by idamir** [comment]
You can try i18nd("domain", "string to translate")
Domain is like a context for translation.

**Pull request merged**
